projects:
  aura:
    name: "Aura Subgraph"
    schemaPath: "./schema.graphql"
    extensions:
      endpoints:
        kovan:
          url: "https://api.thegraph.com/subgraphs/name/0xbutterfield/aura-kovan"
          headers:
            "user-agent": "JS GraphQL"
          introspect: false
